test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

development:
  service: Disk
  root: <%= Rails.root.join("storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Example production configuration (uncomment and configure for S3 or another service)
# production:
#   service: S3
#   access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
#   secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
#   region: <%= ENV["AWS_REGION"] %>
#   bucket: <%= ENV["AWS_S3_BUCKET"] %>